=== tellgeniewish/Web-Service/XMLExamples/week03/BookML.dtd
<!ENTITY % commonBookInfo "title, author+, publisher, publishDate, price, pages, rating, coverImage*, description*, review*"><!-- R2 -->
<!ENTITY % dateAttr "year CDATA #REQUIRED
					 month (01|02|03|04|05|06|07|08|09|10|11|12) #REQUIRED
					 day CDATA #REQUIRED"><!-- R4 -->
<!ENTITY % priceAttr "(won|dollar|yen)">
<!ENTITY % periodAttr "day (01|02|03|04|05|06|07|08|09|10|11|12|13|14) #REQUIRED">
<!ENTITY SO "생각 중독 불안과 후회를 끊어내고 오늘을 사는 법"><!-- 나.2 -->

<!ELEMENT catalog (bookList, bookCategory)><!-- R1 -->

<!ELEMENT bookList (book*, eBook, newEBook)>

<!ELEMENT bookCategory (category+)>
<!ELEMENT category (#PCDATA|category)*><!-- R12 -->
<!ATTLIST category cid ID #REQUIRED
					name CDATA #REQUIRED><!-- R3 -->
					
<!ELEMENT book (%commonBookInfo;, revisionDate*)><!-- R2 -->
<!ELEMENT eBook (%commonBookInfo;, revisionDate*, originalTitle, translator, format, size, period*)><!-- R9 -->
<!ELEMENT newEBook (%commonBookInfo;, originalTitle, format, size, period*)><!-- R11 -->

<!ATTLIST book id ID #REQUIRED
			   categories IDREFS #REQUIRED>
<!ATTLIST eBook id ID #REQUIRED
			   categories IDREFS #REQUIRED>
<!ATTLIST newEBook id ID #REQUIRED
			   categories IDREFS #REQUIRED>

<!ELEMENT title (#PCDATA)>
<!ELEMENT originalTitle (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT translator (#PCDATA)>
<!ELEMENT publisher (#PCDATA)>
<!ELEMENT publishDate (#PCDATA)>
<!ATTLIST publishDate %dateAttr;><!-- R4 -->

<!ELEMENT revisionDate (#PCDATA)>
<!ATTLIST revisionDate %dateAttr;><!-- R4 -->

<!ELEMENT price (listPrice, salesPrice)>
<!ATTLIST price currency %priceAttr; "won"><!-- R5 -->
<!ELEMENT listPrice (#PCDATA)>
<!ELEMENT salesPrice (#PCDATA)>
<!ATTLIST salesPrice discountRate CDATA #IMPLIED>

<!ELEMENT pages (#PCDATA)><!-- R6 -->
<!ELEMENT description (#PCDATA)>
<!ELEMENT rating (#PCDATA)>

<!ELEMENT review (#PCDATA)>

<!ELEMENT format (#PCDATA)>
<!ATTLIST format value (EPUB|pdf|StreamText|StreamImage) #REQUIRED><!-- R10 -->

<!ELEMENT size (#PCDATA)>
<!ATTLIST size unit (KB|MB|GB) #REQUIRED>

<!ELEMENT period (#PCDATA)>

<!ELEMENT coverImage (#PCDATA)>
<!ATTLIST coverImage src CDATA #REQUIRED 
					 type NOTATION (jpeg|gif|png) #REQUIRED><!-- R8 -->
<!NOTATION jpeg PUBLIC "image/jpeg" "imageViewer.exe">
<!NOTATION gif PUBLIC "image/gif" "photoViewer.exe">
<!NOTATION png PUBLIC "image/png">

=== tellgeniewish/Web-Service/XMLExamples/week03/BookML.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE catalog SYSTEM "BookML.dtd" 
[<!ENTITY SO "생각 중독 불안과 후회를 끊어내고 오늘을 사는 법">]>
<catalog>
  <bookList>
    <book id="isbn-895468000-3" categories="c101-1-1">
      <title>>이토록 평범한 미래</title>
      <author>김연수</author>
      <publisher>문학동네</publisher>
      <publishDate year="2022" month="10" day="07" />
      <!-- 다음과 같은 형식도 가능:
      <publishDate>
      <year>2022</year><month>10</month><day>07</day>
      </publishDate> -->
      <price currency="won">
        <listPrice>14000</listPrice>
        <salesPrice discountRate="10">12600</salesPrice>
      </price>
      <!-- 다음과 같은 형식도 가능:
      <price currency="won" listPrice="14000" salesPrice="12600" discountRate="10" /> -->
      <pages>276</pages>
      <rating>9.4</rating>
      <coverImage src="https://image.yes24.com/goods/113737429/XL" type="jpeg" />
      <description>김연수 9년 만의 신작 소설집. 종말 이후의 사랑에 대한 여덟 편의 이야기. 작가가
      최근 2~3년간 집중적으로 단편 작업에 매진한 끝에 선보이는 소설집으로, '시간'을 인식하는 김연수의 변화된
      시각을 확인할 수 있게 한다. 김연수는 과거에서 미래를 향해 흐르는 것으로만 여겨지는 시간을 다르게 정의
      함으로써 우리가 현재의 시간을, 즉 삶을 새롭게 상상할 수 있는 가능성을 아름답고 서정적인 언어로 설득해
      낸다. 특별한 점은 그 가능성이 '이야기'의 형태로 전달된다는 것이다. …
      </description>
      <review>"우리가 달까지 갈 수는 없지만 갈 수 있다는 듯이 걸어갈 수는 있다. 달이 어디에 있
      는지 찾을 수만 있다면. 마찬가지로 우리는 달까지 걸어가는 것처럼 살아갈 수 있다. 희망의 방향만 찾을 수
      있다면." (-&lt;진주의 결말&gt; 중에서) 어떤 희망의 방향을 찾는 일은 때로 쉽고 어렵다. 이런 소설을 읽으
      면서 작은 격려와 응원을 받는 기분이다. 좋은 소설에 대해, 우리가 기다렸던 소설이 이런 게 아닐까 싶
      다.</review> <!-- 나.2 -->
      <revisionDate year="2023" month="11" day="15" /> 
    </book>
    <eBook id="isbn-978-893497246-4" categories="c102-1 c103-2">
      <title>사피엔스</title>
      <author>유발 하라리</author>
      <publisher>김영사</publisher>
      <publishDate day="" month="01" year="">publishDate</publishDate>
      <price currency="won">
        <listPrice>listPrice</listPrice>
        <salesPrice discountRate="">salesPrice</salesPrice>
      </price>
      <pages>pages</pages>
      <rating>rating</rating>
      <coverImage src="" type="jpeg">coverImage</coverImage>
      <description>변방의 유인원 호모 사피엔스는 어떻게 세상의 지배자가 되었는가? 수렵채집을 하
      던 우리 조상들은 어떻게 한 곳에 모여 도시와 왕국을 건설하였는가? 인간은 왜 지구 역사상 가장 치명적인
      동물이 되었는가? 과학은 모든 종교의 미래인가? 인간의 유효기간은 언제까지인가? 멀고먼 인류의 시원부터
      인지혁명, 농업혁명, 과학혁명을 거쳐 끊임없이 진화해온 인간의 역사를 생물학, 경제학, 종교학, 심리학, 철학
      등 여러 학문의 경계를 넘나들며 다양하고 생생하게 조명한 전인미답의 문제작. 호모 사피엔스부터 인공지능
      까지, 기나긴 역사의 시간을 한 권으로 써내려간 문명 항해기.</description>
      <review>review</review>
      <originalTitle>Sapiens: A Brief History of Humankind &amp; Earth</originalTitle>
      <translator>조현욱</translator>
      <format value="EPUB"/>
      <size unit="MB">26.60</size>
      <period>30</period>
    </eBook>
    <newEBook id="isbn-978-890128069-1" categories="c102-2">
      <title>생각 중독: 불안과 후회를 끊어내고 오늘을 사는 법</title>
      <author>닉 트렌턴</author>
      <publisher>publisher</publisher>
      <publishDate year="2024" month="02" day="29" />
      <price currency="won">
        <listPrice>listPrice</listPrice>
        <salesPrice discountRate="">salesPrice</salesPrice>
      </price>
      <pages>pages</pages>
      <rating>rating</rating>
      <coverImage src="" type="jpeg">coverImage</coverImage>
      <description>description</description>
      <originalTitle>&SO;</originalTitle>
      <format value="pdf"/>
      <size unit="MB">83.88</size>
      <period>14</period>
    </newEBook>
  </bookList>
  <bookCategory>
 <category cid="c101" name="문학">
 <category cid="c101-1" name="소설"> 
 <category cid="c101-1-1" name="한국소설"> ... </category>
 <category cid="c101-1-2" name="영미소설"> ... </category> 
 </category> 
 <category cid="c101-2" name="시"> ... </category>
 <category cid="c101-3" name="희곡"> ... </category> 
 </category>
 <category cid="c102" name="인문"> 
 <category cid="c102-1" name="철학/사상"> ... </category>
<category cid="c102-2" name="심리학"> ... </category>
 </category>
 <category cid="c103" name="역사"> 
 <category cid="c103-1" name="한국사"> ... </category>
 <category cid="c103-2" name="세계사"> ... </category>
 </category>
 </bookCategory>

</catalog>
