=== tellgeniewish/Web-Service/XMLExamples/week05/BooML.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
		targetNamespace="http://www.dongduk.ac.kr/bookML/2.0"
		xmlns:tns="http://www.dongduk.ac.kr/bookML/2.0"
		elementFormDefault="qualified">
		<!-- targetNamespace 버전 수정 ㄱㄴ -->

	<simpleType name="ISBNType"> <!-- ISBN -->
		<restriction base="string">
			<pattern value="\d{9}-\d|(987|979)-\d{9}-\d" />
		</restriction>
	</simpleType>

	<complexType name="priceType"> <!-- 가격 / currency 속성의 기본값은 "won" -->
		<sequence>
			<element name="listPrice" type="decimal" />
			<element name="salesPrice">
				<complexType>
					<simpleContent>
						<extension base="decimal">
							<attribute name="DiscountRate" type="tns:DiscountRateType" />
						</extension>
					</simpleContent>
				</complexType>
			</element>
		</sequence>
		<attribute name="currency" type="tns:currencyType" default="won" />
	</complexType>

	<simpleType name="currencyType"> <!-- currency 종류 -->
		<restriction base="string">
			<enumeration value="won" />
			<enumeration value="dollar" />
			<enumeration value="yen" />
		</restriction>
	</simpleType>

	<simpleType name="DiscountRateType"> <!-- 할인율 -->
		<restriction base="integer">
			<minInclusive value="0" />
			<maxInclusive value="90" />
		</restriction>
	</simpleType>

	<simpleType name="PagesType"> <!-- 페이지 수 -->
		<restriction base="integer">
			<minInclusive value="1" />
			<maxInclusive value="1000" />
		</restriction>
	</simpleType>

	<simpleType name="RatingType"> <!-- 평점 -->
		<restriction base="decimal">
			<minInclusive value="1" />
			<maxInclusive value="10" />
		</restriction>
	</simpleType>

	<complexType name="FileFormatType"> <!-- eBook 파일 포맷 -->
		<attribute name="value">
			<simpleType>
				<restriction base="string">
					<enumeration value="EPUB" />
					<enumeration value="PDF" />
					<enumeration value="StreamText" />
					<enumeration value="StreamImage" />
				</restriction>
			</simpleType>
		</attribute>
	</complexType>

	<complexType name="FileSizeType"> <!-- 파일 크기 -->
		<simpleContent>
			<extension base="decimal">
				<attribute name="unit" type="string" />
			</extension>
		</simpleContent>
	</complexType>

	<!-- NOTATION 선언 -->
   <notation name="jpeg" public="image/jpeg" system="imageViewer.exe" />
   <notation name="gif" public="image/gif" system="imageViewer.exe" />
   <notation name="png" public="image/png" system="imageViewer.exe" />

	<complexType name="bookCoverType">  <!-- 표지 그림 -->
		<attribute name="src" type="anyURI" />
		<attribute name="type">
			<simpleType>
				<restriction base="NOTATION">
					<enumeration value="tns:jpeg" />
					<enumeration value="tns:gif" />
					<enumeration value="tns:png" />
				</restriction>
			</simpleType>
		</attribute>
	</complexType>
	
	<complexType name="bookType"> <!-- book -->
		<sequence>
			<element name="title" type="string" />
			<element name="originalTitle" type="string" minOccurs="0" />
			<choice>
            	<element name="author" type="string" maxOccurs="unbounded" minOccurs="1"></element>
            	<element name="writer" type="string" maxOccurs="unbounded" minOccurs="1"></element>
         	</choice>
			<element name="translator" type="string" minOccurs="0" />
			<element name="publisher" type="string" />
			<element ref="tns:publishDate" />
			<element ref="tns:revisionDate" minOccurs="0" maxOccurs="unbounded" />
			<element name="price" type="tns:priceType" />
			<element name="pages" type="tns:PagesType" />
			<element name="rating" type="tns:RatingType" />
			<element name="category" type="string" minOccurs="0" maxOccurs="unbounded" />
			<element name="coverImage" type="tns:bookCoverType"	minOccurs="0" />
			<element name="description" type="string" minOccurs="0" />
			<element name="review" type="string" minOccurs="0" maxOccurs="20" />
		</sequence>
		<attribute name="isbn" type="tns:ISBNType" use="required" />
	</complexType>
	
	<complexType name="eBookType"> <!-- eBook -->
		<complexContent>
			<extension base="tns:bookType">
				<sequence>
					<element name="format" type="tns:FileFormatType" />
					<element name="size" type="tns:FileSizeType" />
					<element name="period" type="positiveInteger" />
				</sequence>
			</extension>
		</complexContent>
	</complexType>

	<complexType name="newEBookType"> <!-- newEBook -->
		<complexContent>
			<restriction base="tns:eBookType">
				<sequence>
					<element name="title" type="string" />
					<element name="originalTitle" type="string" minOccurs="0" />
					<choice>
		            	<element name="author" type="string" maxOccurs="unbounded" minOccurs="1"></element>
		            	<element name="writer" type="string" maxOccurs="unbounded" minOccurs="1"></element>
		         	</choice>
		         	<element name="translator" type="string" minOccurs="0" />
					<element name="publisher" type="string" />
					<element ref="tns:publishDate" />
					<element ref="tns:revisionDate" minOccurs="0" maxOccurs="0" />
					<element name="price" type="tns:priceType" />
					<element name="pages" type="tns:PagesType" />
					<element name="rating" type="tns:RatingType" />
					<element name="category" type="string" minOccurs="0" maxOccurs="unbounded" />
					<element name="coverImage" type="tns:bookCoverType"	minOccurs="0" />
					<element name="description" type="string" minOccurs="0" />
					<element name="review" type="string" minOccurs="0" maxOccurs="20" />
					<element name="format" type="tns:FileFormatType" />
					<element name="size" type="tns:FileSizeType" />
					<element name="period">
						<simpleType>
							<restriction base="positiveInteger">
							<maxInclusive value="14"></maxInclusive>
							</restriction>
						</simpleType>
					</element>
				</sequence>
			</restriction>
		</complexContent>
	</complexType>

	<complexType name="CategoryType">
		<sequence>
			<element name="category" type="tns:CategoryType" minOccurs="0" maxOccurs="unbounded" />
		</sequence>
		<attribute name="cid" type="string" />
		<attribute name="name" type="string" />
	</complexType>

	<attributeGroup name="dateAttrGroup"> <!-- 년/월/일 -->
		<attribute name="year" use="required">
			<simpleType>
				<restriction base="gYear">
					<minInclusive value="1900" />
					<maxInclusive value="2024" />
				</restriction>
			</simpleType>
		</attribute>
		<attribute name="month" use="required">
			<simpleType>
				<restriction base="string">
					<pattern value="0[1-9]|1[0-2]" />
				</restriction>
			</simpleType>
		</attribute>
		<attribute name="day" use="required">
			<simpleType>
				<restriction base="string">
					<pattern value="0[1-9]|[1-2][0-9]|3[01]" />
				</restriction>
			</simpleType>
		</attribute>
	</attributeGroup>

	<element name="publishDate"> <!-- 출판일 -->
		<complexType>
			<attributeGroup ref="tns:dateAttrGroup" />
		</complexType>
	</element>

	<element name="revisionDate"> <!-- 개정일 -->
		<complexType>
			<attributeGroup ref="tns:dateAttrGroup" />
		</complexType>
	</element>

	<element name="bookList">
		<complexType>
			<sequence>
				<element name="book" type="tns:bookType" minOccurs="0" maxOccurs="unbounded"></element>
			</sequence>
		</complexType>
	</element>

	<element name="bookCategory">
		<complexType>
			<sequence>
				<element name="category" type="tns:CategoryType" minOccurs="0" maxOccurs="unbounded"></element>
			</sequence>
		</complexType>
	</element>

	<element name="catalog"> <!-- 루트 엘리먼트 catalog -->
		<complexType>
			<sequence>
				<element ref="tns:bookList" />
				<element ref="tns:bookCategory" />
			</sequence>
		</complexType>
	</element>

</schema>

=== tellgeniewish/Web-Service/XMLExamples/week05/BookML.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE catalog [
	<!ENTITY favoriteAuthor SYSTEM "김연수">
]>
<catalog xmlns:xsi="http://www.dongduk.ac.kr/bookML/2.0" 
			xmlns="http://www.w3.org/2001/XMLSchema-instance" 
			xsi:schemaLocation="http://www.dongduk.ac.kr/bookML/2.0 BooML.xsd ">
  <bookList>
    <book isbn="895468000-3">
      <title>이토록 평범한 미래</title>
      <author>&favoriteAuthor;</author>
      <translator>문학동네</translator>
      <publishDate day="07" month="10" year="2022"/>
      <revisionDate day="15" month="11" year="2023"/>
      <price currency="won">
        <listPrice>14000</listPrice>
        <salesPrice DiscountRate="10">12600</salesPrice>
      </price>
      <pages>276</pages>
      <rating>9.4</rating>
      <category>c101-1-1</category>
      <coverImage src="http://image.yes24.com/goods/113737429/XL" type="jpeg"/>
      <description>김연수는 9년 만의 신작 소설집. 종말 이후의 사라에 대한 여덟 편의 이야기. 작가가 
      최근 2~3년간 집중적으로 단편 작업에 매진한 끝에 선보이는 소설집으로, '시간'을 인식하는 김연수의 변화된 
      시각을 확인할 수 있게 한다...</description>
      <review>"우리가 달까지 갈 수는 없지만 갈 수 있다는 듯이 걸어갈 수는 있다. 달이 어디에 있
      는지 찾을 수만 있다면. 마찬가지로 우리는 달까지 걸어가는 것처럼 살아갈 수 있다. 희망의 방향만 찾을 수
      있다면"(-&lt;진주의 결말&gt; 중에서)...</review>
      <review>...</review>
    </book>
    <book isbn="978-893497246-4" xsi:type="eBookType">
    	<title>사피엔스</title>
    	<originalTitle>Sapiens: A Brief History of Humankind &amp; Earth</originalTitle>
      	<author>유발 하라리</author>
      	<translator>조현욱</translator>
      	<publisher>김영사</publisher>
      	<publishDate day="19" month="05" year="2014"/>
      	<price>
	        <listPrice>12000</listPrice>
	        <salesPrice DiscountRate="20">9600</salesPrice>
	    </price>
	    <pages>241</pages>
	    <rating>9.2</rating>
	    <category>c102-1</category>
	    <category>c103-2</category>
	    <description>변방의 유인원 호모 사피엔스는 어떻게 세상의 지배자가 되었는가? 수렵채집을 하
      던 우리 조상들은 어떻게 한 곳에 모여 도시와 왕국을 건설하였는가? 인간은 왜 지구 역사상 가장 치명적인
      동물이 되었는가? 과학은 모든 종교의 미래인가?...</description>
      <format value="EPUB"/>
      <size unit="MB">26.60</size>
      <period>30</period>
    </book>
    <book isbn="978-890128069-1" xsi:type="newEBookType">
    	<title>생각 중독: 불안과 후회를 끊어내고 오늘을 사는 법</title>
		<originalTitle>Stop Overthinking</originalTitle>
		<author>닉 트렌턴</author>
      	<publishDate day="29" month="02" year="2024"/>
      	<category>c102-2</category>
      <format value="pdf"/>
      <size unit="MB">83.88</size>
      <period>20</period>
    </book>
  </bookList>
  <bookCategory>
    <category cid="c101" name="문학">
      <category cid="c101-1" name="소설"/>
      <category cid="c101-1-1" name="한국소설"></category>
      <category cid="c101-1-2" name="영미소설"></category>
    </category>
  </bookCategory>
</catalog>
