=== tellgeniewish/Web-Service/XMLExamples/week02/bml.dtd
<!ELEMENT booklist (book*)>
<!ELEMENT book (title, author+, publisher, price)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (name, tel, address)> <!-- 모든 엘리먼트가 한 번씩만 정의되어야 한다. author에 자식에 title을 적으면 오류남 -->
<!ELEMENT name (#PCDATA)>
<!ELEMENT tel (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT publisher (#PCDATA)>
<!ELEMENT price (#PCDATA)>

<!-- 속성 선언 -->
<!ATTLIST book id ID #REQUIRED
				kind (컴퓨터|소설|언어) #IMPLIED>
<!ATTLIST name sex (man|woman) #REQUIRED>

=== tellgeniewish/Web-Service/XMLExamples/week02/c4_1501.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE booklist SYSTEM "bml.dtd" >
<booklist>
  <book id="idvalue0" kind="컴퓨터">
    <title>title</title>
    <author>
      <name sex="man">name</name>
      <tel>tel</tel>
      <address>address</address>
    </author>
    <publisher>publisher</publisher>
    <price>price</price>
  </book>
</booklist>
